### ISSUE TITLE
scorebing bloqueando ip... poderia ajudar?

### ISSUE THREAD

**Issue by halleybr** [MatheusGatti/Soccer-Corners-Crawler-and-Bot#2]
Boa tarde,

ele funciona a primeira vez que roda porém depois o site que busca os jogos e resultados bloqueia o meu ip fixo 

Your IP (187.16.114.21) is blocked since the system detected there are some abuses from it. If any problem, please contact us at support@scorebing.com.

poderia ajudar saber se posso buscar estatisticas de outro site parecido??

Obrigado demais.

**Comment by MatheusGatti** [comment]
O site bloqueia mesmo, você pode ou trocar seu IP, ou usar uma VPN ou proxy. Eu não sei qual outro site parecido existe pois estou fora desse projeto por bastante tempo.
